"""add telegram_tag to chat_members

Revision ID: c9f7bbfa4663
Revises: f97694849192
Create Date: 2026-07-26 14:15:11.642872

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'c9f7bbfa4663'
down_revision: Union[str, None] = 'f97694849192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_tag', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_members', schema=None) as batch_op:
        batch_op.drop_column('telegram_tag')

    # ### end Alembic commands ###
